fieldLayouts:
  08ac5e56-72d7-421d-aad1-a12fdbf5bc1f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fe39373d-b991-41ea-9d74-84a130566d77
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 709bd7f3-74c2-4300-a80a-d2cb773a23fa # Beeld
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ca60c53-ccc1-422b-9f1c-32e28eee9873
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 273b1bc5-81ef-47d1-b139-4bd963a505e8
        userCondition: null
handle: jobs
hasTitleField: true
name: Jobs
section: 44d976c2-3a84-4208-8672-99b816b9db7b # Pagina
sortOrder: 6
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
