query getPage($uri: [String]!) {
  entries(section: "pages", uri: $uri) {
    id
    title
    slug
    typeHandle
    ... on pages_homePage_Entry {
      headerIntro
      headerBgImage {
        id
        url
        alt
      }
      headerIntro
      headerButton {
        ariaLabel
        customText
        target
        text
        title
        type
        url
      }
      contentGrid {
        ...matrixFields
      }
    }
  }
}
