field: 432cafcd-9d3b-4780-a696-4f52c651f7bb # Inhoud
fieldLayouts:
  b6c12f24-983d-4748-89c8-dcef8c90f290:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d763e1fb-8e34-4de9-9b60-06000329c7a4 # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 238fa922-c416-4882-b2e6-34d872b3cccb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7a0703fc-03bb-4187-aea6-c188c84bc4cf # Formulier
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a065a15-454c-490e-8e4d-4e94d84a3eae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50c3a20a-7045-4d1a-a7dd-38f5b632c5b3
        userCondition: null
fields:
  7a0703fc-03bb-4187-aea6-c188c84bc4cf: # Formulier
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: formie
    instructions: null
    name: Formulier
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
  d763e1fb-8e34-4de9-9b60-06000329c7a4: # Titel
    columnSuffix: hksaubts
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Titel
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Heading.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: form
name: Formulier
sortOrder: 9
