field: 432cafcd-9d3b-4780-a696-4f52c651f7bb # Inhoud
fieldLayouts:
  3b02c22f-dc55-4778-9801-78b3b806d926:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc62912b-c8f8-41f3-8983-bc845a547949 # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 004ae359-e60a-46fb-881f-1c097e0045a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9008cd2f-b146-48cf-9444-822947608729 # Jobs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 717333ea-1ea5-4e7b-a45c-347c82a4efd9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ca2128a1-d5cf-4e46-9de7-1219feaccf0f # Knop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c1df3d7-ebe9-4aae-b7ee-7e05ec00f83c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b7d1bd1d-e1c6-433e-8ac6-314bd1c313fc # Achtergrond
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df92e9c4-b869-4217-b81e-49ad93ce518f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87a669b7-6f20-4145-b6be-dd645d5a56ef # Extra ruimte onderaan
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79ac812e-5a55-414a-8ad9-2d3bfd6ea442
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 36d46b57-a1a1-4b99-9e7e-66b53c370534
        userCondition: null
fields:
  87a669b7-6f20-4145-b6be-dd645d5a56ef: # Extra ruimte onderaan
    columnSuffix: akpanuyf
    contentColumnType: boolean
    fieldGroup: null
    handle: marginBottom
    instructions: 'Enkel van toepassing indien de achtergrond is zwart.'
    name: 'Extra ruimte onderaan'
    searchable: false
    settings:
      default: true
      offLabel: Tonen
      onLabel: Verbergen
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  9008cd2f-b146-48cf-9444-822947608729: # Jobs
    columnSuffix: qcrpgjaw
    contentColumnType: string
    fieldGroup: null
    handle: jobs
    instructions: null
    name: Jobs
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources:
        - 'section:3b426d91-309c-438d-b343-a7367c46583e' # Vacatures
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b7d1bd1d-e1c6-433e-8ac6-314bd1c313fc: # Achtergrond
    columnSuffix: jbhcxxvc
    contentColumnType: boolean
    fieldGroup: null
    handle: bgColor
    instructions: null
    name: Achtergrond
    searchable: false
    settings:
      default: true
      offLabel: Wit
      onLabel: Zwart
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  ca2128a1-d5cf-4e46-9de7-1219feaccf0f: # Knop
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkIt
    instructions: null
    name: Knop
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: custom
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  cc62912b-c8f8-41f3-8983-bc845a547949: # Titel
    columnSuffix: amnmowel
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Titel
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Heading.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: jobs
name: Jobs
sortOrder: 10
