field: 1bd66503-6935-4ec5-a1f8-da4a12f3152c # Skills
fieldLayouts:
  22d2f7b5-98e0-4e28-a045-e6ce377704d0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a1119b45-b804-4753-9b46-8c1bf89b6a9c # Naam
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5e839a0-c2da-4003-be3c-a53ca8d7b607
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 195fe02c-023d-4732-b84f-68e0343c458d # Verwachte niveau
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcab4179-354a-43f2-9e1b-fdd0409911c8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 052bbd8f-2962-4e24-a96a-992af4365353
        userCondition: null
fields:
  195fe02c-023d-4732-b84f-68e0343c458d: # Verwachte niveau
    columnSuffix: akzxbrxu
    contentColumnType: string
    fieldGroup: null
    handle: skillLevel
    instructions: null
    name: 'Verwachte niveau'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '1'
            -
              - value
              - '1'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '2'
            -
              - value
              - '2'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '3'
            -
              - value
              - '3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '4'
            -
              - value
              - '4'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '5'
            -
              - value
              - '5'
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a1119b45-b804-4753-9b46-8c1bf89b6a9c: # Naam
    columnSuffix: sxhohjcu
    contentColumnType: text
    fieldGroup: null
    handle: skillName
    instructions: null
    name: Naam
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: skill
name: Skill
sortOrder: 1
