defaultPlacement: end
enableVersioning: true
handle: collabs
name: Collabs
previewTargets:
  -
    __assoc__:
      -
        - label
        - Nuxt
      -
        - urlFormat
        - 'http://localhost:3000/{uri}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  19424c73-8f9f-4f98-9003-2f44d57c83df: # headless
    enabledByDefault: true
    hasUrls: true
    template: collabs/_entry
    uriFormat: 'collabs/{slug}'
type: channel
