defaultPlacement: end
enableVersioning: true
handle: jobs
name: Vacatures
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - 'http://localhost:3000/{uri}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  19424c73-8f9f-4f98-9003-2f44d57c83df: # headless
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: 'jobs/{slug}'
type: channel
