columnSuffix: null
contentColumnType: string
fieldGroup: 43a6af1b-ac9a-4cda-b7ac-9c6b0920ceb4 # SuperTable
handle: collabs
instructions: null
name: Collabs
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 122930160
  columns:
    __assoc__:
      -
        - cce12c46-fd32-4504-8a97-800b29f73fd6 # Tekst
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 675b6095-e701-43de-9769-1e3f3970d511 # Knop
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_collabs}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: true
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
