columnSuffix: null
contentColumnType: string
fieldGroup: 11132693-48c5-4573-9509-462841e28f55 # Form
handle: headerForm
instructions: null
name: Formulier
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
