columnSuffix: null
contentColumnType: string
fieldGroup: 43a6af1b-ac9a-4cda-b7ac-9c6b0920ceb4 # SuperTable
handle: socials
instructions: null
name: 'Sociale media'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 262299915
  columns:
    __assoc__:
      -
        - c66e7a55-fab4-442e-8c45-c40e102fcc76 # Platform
        -
          __assoc__:
            -
              - width
              - ''
      -
        - b8e95f72-2bd7-49de-84d0-52ee6ad15163 # Profiel-url
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_socials}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
