field: e6e0f17a-3986-4505-8d3e-93f07374d0ea # Services
fieldLayouts:
  4a9a59fc-f69e-4135-ab11-51ad48ed1d34:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 386f1e6a-81f1-4735-b7b1-6ebd8ca1db4d # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc368a89-758b-44e7-a04d-35dc05995b40
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 045812dd-fa28-4a27-a532-2a113edcfd97 # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c224305-0cab-4bef-ac1b-b0588f2e32a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 01d4c5a8-a2d0-4e45-a6d5-b39459e379d4
        userCondition: null
fields:
  386f1e6a-81f1-4735-b7b1-6ebd8ca1db4d: # Titel
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  045812dd-fa28-4a27-a532-2a113edcfd97: # Tekst
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Tekst
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
