field: 62a3bfe0-7846-4c77-85a2-c116ec10b585 # Blokken
fieldLayouts:
  e993d1b2-9323-48d1-b063-01121f254c0e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 16dc51f3-9ca4-4237-be79-8f2bbdae69a7 # Titel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0669a6f1-520a-49c4-8395-c6ce61358091
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80d2a1e9-c14e-4a51-a30a-7ebf01eafa0e # Tekst
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc1be5d2-f679-44b8-a879-a4f7876253f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4b5e0b2c-7f5a-4259-a18c-c3ec5ef2fade
        userCondition: null
fields:
  16dc51f3-9ca4-4237-be79-8f2bbdae69a7: # Titel
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Titel
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Heading.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  80d2a1e9-c14e-4a51-a30a-7ebf01eafa0e: # Tekst
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Tekst
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
