fragment matrixFields on contentGrid_MatrixField {
    ... on contentGrid_text_BlockType {
        uid
        typeHandle
        text
    }
    ... on contentGrid_image_BlockType {
        uid
        typeHandle
        image{
            url
            alt
        }
    }
    ... on contentGrid_textAndImage_BlockType {
        uid
        typeHandle
        image {
            id
            url
            alt
        }
        heading
        text
        linkIt {
            ariaLabel
            customText
            target
            text
            title
            type
            url
        }
        position
        bgBlack
        marginBottom
    }
    ... on contentGrid_grid_BlockType {
        uid
        typeHandle
        blocks {
            ... on blocks_BlockType {
                heading
                text
            }
        }
        bgColor
        titleSize
        marginBottom
    }
    ... on contentGrid_collabs_BlockType {
        uid
        typeHandle
        heading
        collabs {
            id
            title
            uri
            ...on collabs_collab_Entry {
                snippetImage {
                    url
                    alt
                }
                snippetButtonText
            }
        }
        linkIt {
            ariaLabel
            customText
            target
            text
            title
            type
            url
        }
    }
    ... on contentGrid_quote_BlockType {
        uid
        typeHandle
        quote
    }
      ...on contentGrid_collective_BlockType {
        uid
        typeHandle
        companies {
            ...on collective_Company_Entry{
                title
                image {
                    url
                    alt
                }
                text
                website {
                    ariaLabel
                    customText
                    target
                    text
                    title
                    type
                    url
                }
            }
        }
    }
    ... on contentGrid_services_BlockType {
        uid
        typeHandle
        heading
        services {
            ... on services_BlockType {
                heading
                text
            }
        }
        linkIt {
            ariaLabel
            customText
            target
            text
            title
            type
            url
        }
        marginBottom
    }
    ... on contentGrid_images_BlockType {
        uid
        typeHandle
        heading
        linkIt {
            ariaLabel
            customText
            target
            text
            title
            type
            url
        }
        images {
            url
            alt
        }
    }
    ... on contentGrid_form_BlockType {
        uid
        typeHandle
        heading
        formie {
            ...formFields
        }
    }
    ... on contentGrid_jobs_BlockType {
        uid
        typeHandle
        heading
        jobs {
            id
            title
            url
            uri
            ... on jobs_job_Entry {
                snippetImage {
                    url
                    alt
                }
                snippetText
            }
        }
        linkIt {
            ariaLabel
            customText
            target
            text
            title
            type
            url
        }
        bgColor
        marginBottom
    }
    ... on contentGrid_textCarousel_BlockType {
        uid
        typeHandle
        words {
            ... on words_BlockType {
                word
            }
        }
        direction
    }
    ... on contentGrid_cta_BlockType {
        uid
        typeHandle
        text
        linkIt {
            ariaLabel
            customText
            target
            text
            title
            type
            url
        }
        image {
            url
            slug
        }
        marginBottom
    }
    ... on contentGrid_offices_BlockType {
        uid
        typeHandle
        heading
        offices {
            id
            title
            ...on offices_office_Entry {
                address
                gMapsUrl {
                    url
                }
            }
        }
    }
}